# Generated by Django 2.2.17 on 2020-12-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjg_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_type',
            new_name='atyp',
        ),
    ]
