# Generated by Django 2.2.17 on 2020-12-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjg_base', '0002_auto_20201219_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='atyp',
            new_name='atype',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phone_type',
            new_name='ptype',
        ),
    ]
