# Generated by Django 2.2.17 on 2021-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjg_base', '0004_phone_preferred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(blank=True, default=None, help_text='Group features to toggle an entire set of features together', max_length=15, null=True, verbose_name='Group Code')),
                ('feature_code', models.CharField(help_text='Short identifier for referencing this feature from source code', max_length=30, verbose_name='Feature Identifier')),
                ('feature_title', models.CharField(help_text='Title of the feature (displayed to users)', max_length=80, verbose_name='Feature Title')),
                ('feature_description', models.CharField(blank=True, default=None, help_text='Optional description of the feature (displayed to users)', max_length=500, null=True, verbose_name='Feature Description')),
                ('status', models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('L', 'Limited to Admins')], default='L', help_text='Is this feature active?', max_length=1)),
                ('enable_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('disable_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
