# Generated by Django 2.2.17 on 2021-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjg_base', '0006_auto_20210101_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='XssAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Request path', max_length=200)),
                ('username', models.CharField(blank=True, default=None, help_text='Authenticated username/email', max_length=120, null=True)),
                ('parameter_name', models.CharField(blank=True, default=None, help_text='Parameter name', max_length=80, null=True)),
                ('parameter_value', models.CharField(blank=True, default=None, help_text='Parameter content', max_length=500, null=True)),
                ('review_username', models.CharField(blank=True, default=None, help_text='Reviewed by', max_length=120, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
