# Generated by Django 2.2.17 on 2021-01-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mjg_base', '0007_xssattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xssattempt',
            name='review_username',
        ),
        migrations.RemoveField(
            model_name='xssattempt',
            name='username',
        ),
        migrations.AddField(
            model_name='xssattempt',
            name='reviewer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xss_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xssattempt',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xss_suspects', to=settings.AUTH_USER_MODEL),
        ),
    ]
